#!/bin/bash

set -eu

curdir=$(pwd)

tmp=$(mktemp -d)
mkdir "$tmp/rootfs"
musl-gcc -static ./runner.c -o "$tmp/runner"

plash with-mount --from alpine --apk bash -- cp -r . "$tmp/rootfs"

mkdir            "$tmp/rootfs/opt"
mv "$tmp/runner" "$tmp/rootfs/opt"
cp ./glaze.sh    "$tmp/rootfs/opt"

cd "$tmp/rootfs"
tar -czf "$curdir"/glaze.tar.gz .
